# docker-compose.yml

app:
  image: reaction/app
  ports:
    - "80:3000"
  links:
    - mongo
  environment:
    - ROOT_URL=http://devng.geospatial.com
    - MONGO_URL=mongodb://mongo:27017/meteor

mongo:
  image: mongo:latest
  command: mongod --storageEngine=wiredTiger